### ISSUE TITLE
Update CLI to understand interfaces

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#110]
Per . . 

_Originally posted by @rocketstack-matt in https://github.com/finos-labs/architecture-as-code/pull/109#pullrequestreview-1977156635_
           
Changes have been made to CALM to introduce interfaces, we need to reflect these in the CLI tools.

**Comment by jpgough-ms** [comment]
I don't think #112 fixed this issue, will leave this open for now and assign to @willosborne

**Comment by willosborne** [comment]
As you say @jpgough-ms - 112 solved the problem for a minimal subset of cases but I don't think this is complete. You can work around it as is, but it's painful (needs a lot of duplication) and definitely not ergonomic. I wouldn't call this complete until we can follow refs properly; will be looking to implement this early next week.
