### ISSUE TITLE
Support Metadata Object

### ISSUE THREAD

**Issue by jpgough-ms** [finos/architecture-as-code#183]
### Description of Problem:

Whilst working with systems that practically use CALM nodes and patterns, we have found a need to model additional information or metadata.

### Potential Solutions:

Introduce a common type `metadata` that has an array of objects to allow for extension within the CALM schema.

As owners we will need to be considerate that metadata does not soak from things that should become concrete types in the architecture or pattern

cc/ @rocketstack-matt from our offline discussion for additional comments as needed

**Comment by willosborne** [comment]
This is done. We have generation support that supports generic objects, so I think that's enough for people to fully use this feature.
