### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 23 Jan 2024

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#240]
## Date

Tuesday 23 Jan 2024 - 11:00 EST / 16:00 UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes
- [x] Overview of the new Architecture as Code Monorepo
- [x] Rebranding of the AasC manifest as CALM (Common Architecture Language Model) - naming kudos to @dc-ms 
- [x] Confirm key project / subgroups and agree cadence / contribution commitments
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by ojeb2** [comment]
Oli Bage / LSEG
