### ISSUE TITLE
Version reported is incorrect

### ISSUE THREAD

**Issue by willosborne** [finos/architecture-as-code#283]
## Bug Report
--version always prints 0.1.0 because it's hard coded. This should report current version (without hard coding)

### Steps to Reproduce:
- Install version 0.1.4
- Run --version
- See output

### Expected Result:
0.1.4

### Actual Result:
0.1.0

### Proposed solution
Use the following code in index.ts:
```
import {version} from './package.json';
```
and then print that instead of a hardcoded string.

**Comment by rocketstack-matt** [comment]
Resolves in https://github.com/finos/architecture-as-code/pull/438

**Comment by rocketstack-matt** [comment]
The fix appears to be to use commander.

We need to add to index.ts

```json
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const { version } = require('../package.json');

program
    .version(version)
```

When we build and install the local module as global

```shell
% calm --version
0.2.3
```
