### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 25 June 2024

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#288]
## Date

Tuesday 25 June 2024 - 11:00 EST / 16:00 BST

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |
| Richard Egere | | |
| Janette Schulze | Morgan Stanley | | 
| Meghdeep Basu | Natwest | | 
| Graham Packer | Morgan Stanley | | 
| Michael Finkelstein | | | 
| Aaron Searle | Morgan Stanley | | 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve [previous meeting minutes](https://github.com/finos/architecture-as-code/issues/234)
- [x] [Recap of CALM / AasC](https://github.com/finos/devops-automation/files/13120631/2023-10-24.pdf) and purpose for new joiners (@rocketstack-matt / 5mins)
- [x] Update on "My Secure Bank" (Aldwin / 10 mins)
- [x] Proposed Domain: Resiliency Requirements: walk through of proposed new domain to capture [resiliency requirements in CALM](https://github.com/finos/architecture-as-code/issues/200) ((@develontopia / 20 mins)
- [x] Tentative: Proposed Domains: Observability & Controls (@jpgough-ms / 10 mins)
- [x] Proposed Capability: CALM from Code & Asset Inventory data (@rocketstack-matt / 10 mins)
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items

- [x] Signup volunteers to work on Resiliency Requirements Domain

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/architecture-as-code/

**Project Board:** https://github.com/orgs/finos/projects/98

**Mailing List:** Email devops-automation+subscribe@finos.org to subscribe to our mailing list

**Comment by Budlee** [comment]
Matthew Auburn (Morgan Stanley)

**Comment by aidanm3341** [comment]
Aidan McPhelim // Morgan Stanley

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by aric-rosenbaum** [comment]
Aric Rosenbaum / Red Hat

**Comment by willosborne** [comment]
Will Osborne / Morgan Stanley

**Comment by djohnston89** [comment]
David Johnston, Aric Rosenbaum, Elo Ogwo- Red Hat

**Comment by aldwins-ms** [comment]
Aldwin Saugere / Morgan Stanley

**Comment by dc-ms** [comment]
Denis Coffaro / Morgan Stanley

**Comment by lionking421** [comment]
Prashant Jasani / Morgan Stanley

**Comment by fleureedwards** [comment]
Fleur Edwards | Nomura

**Comment by ojeb2** [comment]
Oli Bage / LSEG

**Comment by amitpNom** [comment]
Amit Popat / Nomura

**Comment by adamdoran** [comment]
Adam Doran / Morgan Stanley

**Comment by yt-ms** [comment]
Yan Tordoff / Morgan Stanley

**Comment by mgasca** [comment]
Miguel Gasca / Morgan Stanley

**Comment by SlavaVedernikov** [comment]
Slava Vedernikov / Solutions Unit

**Comment by rocketstack-matt** [comment]
Minutes courtesy of @dc-ms 

**FINOS Meeting**: June 25, 2024 
**Commenced**: 11:05 EST 
**Introduction / FINOS Disclaimer**: Completed 
**Agenda & Attendance noted** :  https://github.com/finos/architecture-as-code/issues/288 - Done 
Previous minutes approved by attendees and closed out (Issue 194) : https://github.com/finos/architecture-as-code/issues/234   - Done
 
**Recap of CALM / AaC:**
* @rocketstack-matt
* https://github.com/finos/architecture-as-code/issues/200

**My Secure Bank:**
* @aldwinsaugere 
* My Secure Bank is : It’s a mock up application that emulates the behavior of a online banking application
* Intention was to raise security awareness and training to the development community
* Created with contribution from LSEG
* Mocked up Architecture via CALM

**Proposed Domain : Resiliency Requirements:**
* @develontopia 
* https://github.com/finos/architecture-as-code/issues/200
* Share core definitions, scope and taxonomy
* Proposed a rating system based on requirement type
* Capturing details into the model is key
* Working Group Volunteers: Jeanette Schulze (MS) / Denis Coffaro (MS) / Adam Doran (MS) / Aric Rosenbaum (RH) / Marat Khandros (TBD) (RBC)

**Proposed Capability : Observability & Controls:**
* @rocketstack-matt / @willosborne 
* Observing what we intended to build is what’s built
* More to come

**Proposed Capability: CALM from Code & Asset Inventory data**
* @rocketstack-matt 
  * @rocketstack-matt wants to document all systems in his space and how can he generate CALM based on code
  * Exploring LLM’s for source code reference to CALM manifest

**AOB**
* FINOS OSSF hosted in London 
* @rocketstack-matt + @aidanm3341 presenting Keep CALM and Carry on Approving Change

**Adjourned**: 11:56 EST

**Comment by rocketstack-matt** [comment]
Approved at https://github.com/finos/architecture-as-code/issues/308
