### ISSUE TITLE
Unify command interfaces to use the same flags

### ISSUE THREAD

**Issue by willosborne** [finos/architecture-as-code#313]
### Description of Problem:
Currently the different commands have some inconsistencies in their usage that may be confusing to users.
For example, the validate command uses -m or --metaSchemasLocation to set a directory of schemas to load, whereas generate uses -s or --schemaDirectory.

These should be made consistent.

### Potential Solutions:
Use --schemaDirectory in the case given. But we should also consider other parameters.
Documentation should be updated, too.

**Comment by willosborne** [comment]
We should also make the -m flag on validate behave the same as -s on generate - it should recursively traverse the directory and load all schemas. Currently it only looks at the top level folder.

**Comment by rocketstack-matt** [comment]
I may have inadvertently resolved this with https://github.com/finos/architecture-as-code/pull/530 as I moved the params to be const strings.

**Comment by aidanm3341** [comment]
I was just looking at that s well @rocketstack-matt, but I think the extracted flags still have the same issue. I'll delete one and update the commands to use the same const.

**Comment by aidanm3341** [comment]
addressed in #571
