### ISSUE TITLE
Display error messages first on validation

### ISSUE THREAD

**Issue by willosborne** [finos/architecture-as-code#315]
### Description of Problem:
When the validate command runs, it outputs a big list of JSON messages.
Errors do not appear at the top, so it can be non-obvious which ones are causing the build to fail.

### Potential Solutions:
Sort the validation messages so errors appear first. 

There's also an argument that errors should appear **last** so they appear at the bottom of the output and don't require scrolling - but I feel like this is a bit counter intuitive and would be better replaced with some kind of table view or summary (which I'm raising a separate issue for.)

**Comment by lbulanti-ms** [comment]
This issue has been addressed and will be included in the next release.
