### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 27th August

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#360]
## Date

Tuesday 27th August - 11:00 EST / 16:00 BST

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |
|Vladimir Sergienko | Morgan Stanley | |
|Raymond | | |
|Elisha Amenuveve | | |
|Konadu Appiah | | |
|Dorothy Ewuah | | |
|Mark O'Dell | RedHat | |
|Jonathan Smith | Microsoft | |
|Julian | | |
|Shaun McCloskey | | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve [previous meeting minutes](https://github.com/finos/architecture-as-code/issues/308)
- [x] [Recap of CALM / AasC](https://github.com/finos/devops-automation/files/13120631/2023-10-24.pdf) and purpose for new joiners if needed (@rocketstack-matt / 5mins)
- [x] OSFF Updates (@dc-ms / 5 mins)
- [x] Update on Resiliency Requirements (@develontopia / 5 mins)
- [x] Control Requirements (@jpgough-ms / 30 mins)
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/architecture-as-code/

**Project Board:** https://github.com/orgs/finos/projects/98

**Mailing List:** Email devops-automation+subscribe@finos.org to subscribe to our mailing list

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by matthewgardner** [comment]
Matthew Gardner / Morgan Stanley

**Comment by aidanm3341** [comment]
Aidan McPhelim / Morgan Stanley

**Comment by willosborne** [comment]
Will Osborne / Morgan Stanley

**Comment by george-ball** [comment]
George  Ball / Independent

**Comment by mgasca** [comment]
Miguel Gasca / Morgan Stanley

**Comment by Budlee** [comment]
Matthew Auburn / Morgan Stanley

**Comment by dc-ms** [comment]
Denis Coffaro / Morgan Stanley

**Comment by fleureedwards** [comment]
Fleur Edwards / Nomura

**Comment by bakerwe** [comment]
Edi Baker-Wells / Natwest

**Comment by yt-ms** [comment]
Yan Tordoff /  Morgan Stanley

**Comment by goldelox** [comment]
Shari Lines / Morgan Stanley

**Comment by dc-ms** [comment]
OSFF NYC Details : •	https://events.linuxfoundation.org/open-source-finance-forum-new-york/

**Comment by rocketstack-matt** [comment]
[OSFF Presentation on YouTube](https://www.youtube.com/watch?v=pKjRSMQjy6E) & [Powerpoint deck](https://github.com/rocketstack-matt/architecture-as-code/blob/osff/FINOS%20OSFF%20June%2024.pptx) shown briefly in the working group.

**Comment by karlmoll** [comment]
Two in-person events the same day, at MSFT offices in Times Square

AI Readiness SIG (Members Only)
https://www.finos.org/hosted-events/2024-09-12-ai-readiness-sig-nyc
 
Tech Sprint (TraderX: there is an ongoing initiative which is very relevant to AaC):
https://www.finos.org/hosted-events/2024-09-12-finos-tech-sprint-coding-session

**Comment by charleyalpha789** [comment]
Christopher Avalos / Goldman Sachs

**Comment by djohnston89** [comment]
Red Hat
- David Johnston
- Anurag Saran
- Naaz Page

**Comment by djohnston89** [comment]
Broken URL in Agenda:

Project Board: https://github.com/orgs/finos/projects/98

**Comment by DorothyEwuah** [comment]
Dorothy Ewuah / Turntabl

**Comment by rocketstack-matt** [comment]
> Broken URL in Agenda:
> 
> Project Board: https://github.com/orgs/finos/projects/98

Project boards are only visible to repo members

**Comment by skiddow123** [comment]
Abdul Faheem Kassim / Turntabl

**Comment by YoofiBP** [comment]
Joseph Peter Yoofi Brown-Pobee / turntabl

**Comment by rocketstack-matt** [comment]
**FINOS Meeting** August 27, 2024 
**Commenced** 11:02 EST 
**Introduction / FINOS Disclaimer** Completed 
**Agenda & Attendance noted** https://github.com/finos/architecture-as-code/issues/360 - Done
**Previous minutes approved by attendees and closed out** https://github.com/finos/architecture-as-code/issues/308 - Done
 
**August Release (objectives / current state / blockers)**
 * CALM Overview for new joiners @rocketstack-matt 
  * Brief overview and introduction
  * Relationships/Intentions
  * Nodes explained
  * Instances lead us to Patterns
  * Link to presentation and OSFF London video : https://github.com/finos/architecture-as-code/issues/360#issuecomment-2312858289 
 
* OSFF Update @dc-ms 
  * OSFF FINOS NYC Event
  * September 30 – October 1
  * Multiple CALM related presentations
  * CALM specific on October 1st – 3:45PM EST 
  * Based on issues and questions that were asked – using the platform to review 
    * Problem statement
    * Industries
    * Solutions
    * Domains – Janette (@develontopia)
  * Co present with David Johnson from Red Hat sharing a field perspective
  * Objective is awareness, contribution and consumption
  * https://events.linuxfoundation.org/open-source-finance-forum-new-york/ 
  * API Days London (Link will be in an issue)
  * Security Domains + Observability – (Link will be in an issue) 
* Functional Update @jpgough-ms 
  * Schema and Model 
  * Domains
  * Controls
* Resiliency Domain
  * Christopher Avalos to sync up with Janette Schulze
  * General discover on more contributors in this space

**Issues** https://github.com/finos-labs/architecture-as-code/issues 
**Adjourned** 12:01 EST

**Comment by Elisha-Veve** [comment]
Elisha Amenuveve / Turntabl

**Comment by KapisKay** [comment]
Konadu Appiah / Turntabl

**Comment by rocketstack-matt** [comment]
Approved at https://github.com/finos/architecture-as-code/issues/394
