### ISSUE TITLE
Publish CALM schema changes to calm.finos.org

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#428]
### Description of Problem:
We have recently (as of 2024-09) migrated out schema to use the base URI calm.finos.org; we have manually published 2024-09 to the S3 bucket backing the hosting (https://calm.finos.org/draft/2024-09/meta/calm.json), but other versions are not available and new versions are not pushed without manual intervention.

### Potential Solutions:
Add a GitHub Action to sync any changes to the calm/drafts folder in the repo to <our S3 bucket>/drafts 

The following secrets have been added to the repository:
`AWS_S3_ACCESS_KEY`
`AWS_S3_SECRET_ACCESS_KEY`

The bucket address is in repository variable `AWS_S3_BUCKET` without a trailing slash.

**Comment by NandaniThakur** [comment]
@rocketstack-matt, I am new to this.  I want to work on this.

**Comment by rocketstack-matt** [comment]
Hi @NandaniThakur thanks for the offer of help!

Please take a loot at the README in the root of this project for contribution details and code of conduct, but in short you need to fork this repo and raise a PR with your change, I'm happy to assign this issue to you to avoid others accidentally picking it up.

One thing to be aware of, as a FINOS project, you will need to sign the [Contributor License Agreement](https://community.finos.org/docs/governance/software-projects/easycla/#:~:text=You%20can%20sign%20the%20FINOS,%2C%20sole%20proprietors%2C%20etc) either as yourself or else be covered by the CLA of a FINOS member if you work for one.
