### ISSUE TITLE
Introduce TimeUnit Schema

### ISSUE THREAD

**Issue by LeighFinegold** [finos/architecture-as-code#454]
### Description of Problem:
As I define out `control` constraints like SLA, I need to define them in terms of time e.g. service x trades per second.  

### Potential Solutions:
Define a TimeUnit schema def in [core.js](https://github.com/finos/architecture-as-code/blob/main/calm/draft/2024-10/meta/core.json#L25)

**Comment by jpgough-ms** [comment]
It might be better to put this in `units.json` at the same level as `core.json`, this way it can be used by some of the schemas that don't derive from `core.json`

**Comment by rocketstack-matt** [comment]
Resolved by #457
