### ISSUE TITLE
Document the Steps to Republish the CALM CLI to npm

### ISSUE THREAD

**Issue by LeighFinegold** [finos/architecture-as-code#480]
# Issue Request

## Description of Problem:
The `@finos/calm-cli` package on [npm](https://www.npmjs.com/package/@finos/calm-cli) has not been republished for over two months. Without proper documentation, the process of publishing or republishing the package may be unclear to contributors and maintainers.

To ensure smooth updates and consistency in deployment, it is necessary to have a clear guide on how to republish new versions of the CLI package.

**Comment by Thels** [comment]
This is now documented under the `README.md` of the `cli` module.
