### ISSUE TITLE
Publish CALM to SchemaStore

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/architecture-as-code#5]
### Description of Problem:
We want to make it as easy as possible for people to use the CALM manifest, ideally developers IDEs would automatically recognise Architecture as Code manifests and apply autocomplete and validation.

### Potential Solutions:
[SchemaStore](https://schemastore.org/) is a commonly adopted mechanism for publishing schemas, being well integrated to many common tools like IntelliJ and VS Code. Propose we start publishing our manifest via SchemaStore ([details here](https://github.com/rocketstack-matt/schemastore/blob/master/CONTRIBUTING.md)).

* We should decide whether we will contribute a copy of our schema into the SchemaStore repo or set it up as remotely hosted.
* Suggest we agree a recommended file suffix (e.g. *.calm.json, *.calm.yaml, *.calm.yml) which will provide the simplest integration with the schema without developers needing to configure their IDEs.

Other potential options would be to simply self host (currently doing this and versioning via tags) but this provides less integration.

**Comment by Budlee** [comment]
I like the ideal of *.calm.(json/yaml/yml) as our format.

**Comment by Budlee** [comment]
We can submit a copy, however, I would have thought that we keep self hosting until we are ready with **V1** that is agreed upon and then we submit it ti the JSON Schema Store

**Comment by rocketstack-matt** [comment]
There is a remote hosting option, tbh I think that may be best even long term, it can even support multiple versions so would just mean an update to schemastore each time we add a new draft.

**Comment by willosborne** [comment]
I think we should consider removing this from the April milestone (which needs closing) as we aren't planning to do this quite yet given that we don't have a v1 yet.

**Comment by rocketstack-matt** [comment]
Superseded by publication to our our hosting service - http://calm.finos.org/draft
