### ISSUE TITLE
Formal Documentation site is full of issues

### ISSUE THREAD

**Issue by pyousefi** [finos/architecture-as-code#537]
## Bug Report
Your Docusaurus site did not load properly.

A very common reason is a wrong site [baseUrl configuration](https://docusaurus.io/docs/docusaurus.config.js/#baseUrl).

Current configured baseUrl = / (default value)

We suggest trying baseUrl = /architecture-as-code/
Go to https://finos.github.io/architecture-as-code.

Any link:
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.
### Steps to Reproduce:
 1. Navigate to https://finos.github.io/architecture-as-code/ in your browser to see the first issue
 2. Click on any hyperlink to get the 404

### Expected Result:
A functional website.

**Comment by rocketstack-matt** [comment]
Thanks for the feedback, we don't actually use GitHub Pages for hosting anymore (although they are still published there) - where did you find that link so I can remove it?

You should see that correct location for the docs in the About section of this repo at https://calm.finos.org/
