### ISSUE TITLE
Add arrow labels on graph outputted by calm-visualizer

### ISSUE THREAD

**Issue by oliviajanejohns** [finos/architecture-as-code#567]
## Feature Request
Following on from the following PR https://github.com/finos/architecture-as-code/pull/487. The graph generated should include labels on the arrows to indicate relationships 

<img width="1792" alt="377493798-cf146aec-58f2-4e5d-9b5e-a6374a8194bb-2" src="https://github.com/user-attachments/assets/f254e201-cddd-43a7-9549-841a8b830f15">

**Comment by oliviajanejohns** [comment]
Created a PR for this! But unable to assign this task to myself - apologies

**Comment by dc-ms** [comment]
Assigned to Olivia.
