### ISSUE TITLE
Run CLI validations against patterns and samples via GitHub action

### ISSUE THREAD

**Issue by willosborne** [finos/architecture-as-code#97]
## Feature Request
Once CLI is ready we need to ensure all validations, spectral + JSON Schema, are run against patterns and samples in the repo whenever something changes.
Combined with #96 this will give us confidence that patterns are staying in sync with the CALM spec

### Description of Problem:
Samples and patterns are only validated via spectral currently

### Potential Solutions:
- Run CLI against all patterns and samples
- CLI may need augmenting to support globs to avoid running executable many times

**Comment by jpgough-ms** [comment]
@willosborne I think we are doing this now, so I'm going to close it. If you disagree please re-open
